### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by ateruel** [benhuson/expire-users#33]
Hi

I made an french translation for your plugin
# Copyright (C) 2013 Expire Users
# This file is distributed under the same license as the Expire Users package.

msgid ""
msgstr ""
"Project-Id-Version: Expire Users 0.5\n"
"Report-Msgid-Bugs-To: http://wordpress.org/tag/expire-users\n"
"POT-Creation-Date: 2014-05-15 10:31-0000\n"
"PO-Revision-Date: 2015-03-08 10:47+0100\n"
"Last-Translator: Ben Huson ben@thewhiteroom.net\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.7.4\n"
"X-Poedit-KeywordsList: __;_e;_n;_x;_nx;_ex\n"
"X-Poedit-Basepath: ./\n"
"Language-Team: \n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Language: fr_FR\n"
"X-Poedit-SearchPath-0: ..\n"
# : ../admin/expire-user.php:37 ../admin/expire-user.php:120

msgid "Expire Date"
msgstr "Date de fin de validité"
# : ../admin/expire-user.php:54

msgid "(expired)"
msgstr "(Expiré)"
# : ../admin/expire-user.php:117 ../admin/help.php:36

msgid "User Expiry Information"
msgstr "Informations sur la date d'expiration"
# : ../admin/expire-user.php:125 ../admin/expire-user.php:281

msgid "Edit"
msgstr "Modifier"
# : ../admin/expire-user.php:131 ../admin/settings.php:111
# : ../admin/settings.php:114

msgid "Expiry Date"
msgstr "Date de fin de validité"
# : ../admin/expire-user.php:134 ../admin/settings.php:117

msgid "Never"
msgstr "Jamais"
# : ../admin/expire-user.php:138 ../admin/settings.php:121

msgid "In"
msgstr "Dans"
# : ../admin/expire-user.php:145 ../admin/settings.php:128

msgid "On"
msgstr "Le"
# : ../admin/expire-user.php:160 ../admin/settings.php:140

msgid "On Expire, Default to Role"
msgstr "Rôle par défaut à la date de fin de validité"
# : ../admin/expire-user.php:164 ../admin/settings.php:143

msgid "Don't change role"
msgstr "Ne pas modifier le rôle"
# : ../admin/expire-user.php:171 ../admin/expire-user.php:174
# : ../admin/settings.php:149 ../admin/settings.php:152

msgid "Expire Actions"
msgstr "Règles d'expiration"
# : ../admin/expire-user.php:177 ../admin/settings.php:155

msgid "Replace user's password with a randomly generated one"
msgstr ""
"Remplacer le mot de passe de l'utilisateur avec un nouveau mot de passe "
"généré aléatoirement"
# : ../admin/expire-user.php:181 ../admin/settings.php:159

msgid "Remove expiry details and allow user to continue to login"
msgstr ""
"Effacer la date de fin de validité et permettre à l'utilisateur de continuer "
"à s'identifier"
# : ../admin/expire-user.php:187 ../admin/expire-user.php:190
# : ../admin/settings.php:165 ../admin/settings.php:168

msgid "Email Notifications"
msgstr "Notifications par email"
# : ../admin/expire-user.php:211

msgid "View and configure messages"
msgstr "Voir et configurer les messages"
# : ../admin/expire-user.php:226

msgid "days"
msgstr "jours"
# : ../admin/expire-user.php:227

msgid "weeks"
msgstr "semaines"
# : ../admin/expire-user.php:228

msgid "months"
msgstr "mois"
# : ../admin/expire-user.php:229

msgid "years"
msgstr "années"
# : ../admin/expire-user.php:243

msgid "Jan"
msgstr "Jan"
# : ../admin/expire-user.php:244

msgid "Feb"
msgstr "Fév"
# : ../admin/expire-user.php:245

msgid "Mar"
msgstr "Mars"
# : ../admin/expire-user.php:246

msgid "Apr"
msgstr "Avr"
# : ../admin/expire-user.php:247

msgid "May"
msgstr "Mai"
# : ../admin/expire-user.php:248

msgid "Jun"
msgstr "Juin"
# : ../admin/expire-user.php:249

msgid "Jul"
msgstr "Juil"
# : ../admin/expire-user.php:250

msgid "Aug"
msgstr "Août"
# : ../admin/expire-user.php:251

msgid "Sep"
msgstr "Sept"
# : ../admin/expire-user.php:252

msgid "Oct"
msgstr "Oct"
# : ../admin/expire-user.php:253

msgid "Nov"
msgstr "Nov"
# : ../admin/expire-user.php:254

msgid "Dec"
msgstr "Déc"
# : ../admin/expire-user.php:280

msgid "Cancel"
msgstr "Annuler"
# : ../admin/help.php:37 ../admin/help.php:57

msgid ""
"<p>Activate and configure default expiry settings for users who register via "
"the registration form.</p>"
msgstr ""
"<p>Activer et configurer les paramètres d'expiration par défaut pour les "
"utilisateurs qui se inscrivent via le formulaire d'inscription.</p>"
# : ../admin/help.php:38 ../admin/help.php:58

msgid ""
"<p><strong>Expiry Date</strong><br />Set a user to nevr expire, expire after "
"a period of time or on a specific date.</p>"
msgstr ""
"<p><strong>Date de fin de validité</strong><br />Définir un utilisateur à "
"expiration nevr, expire après une période de temps ou à une date précise. </"
"p>"
# : ../admin/help.php:39 ../admin/help.php:59

msgid ""
"<p><strong>Default to Role</strong><br />When a user expires, you can assign "
"them a different role.</p>"
msgstr ""
"<p><strong>Rôle par défaut</strong> <br />Quand un utilisateur expire, vous "
"pouvez leur attribuer un rôle différent.</p>"
# : ../admin/help.php:40 ../admin/help.php:60

msgid ""
"<p><strong>Expire Actions</strong><br />Other actions to trigger when a user "
"expires:</p>"
msgstr ""
"<p><strong>Règles d'expiration</strong><br />Autres actions à déclencher "
"quand la date de fin de validité est atteinte :</p>"
# : ../admin/help.php:42 ../admin/help.php:62

msgid "<li>replace user's password with a randomly generated one.</li>"
msgstr ""
"<li>Remplacer le mot de passe de l'utilisateur avec un nouveau mot de passe "
"généré aléatoirement.</li>"
# : ../admin/help.php:43 ../admin/help.php:63

msgid "<li>remove expiry details and allow user to continue to login.</li>"
msgstr ""
"<li>Supprimer la date de fin de validité et permettre à l'utilisateur de "
"continuer à d'identifier.</li>"
# : ../admin/help.php:45
# , php-format

msgid ""
"<p><strong>Notification Emails</strong><br />These emails are sent if you "
"have checked the checkboxes on a user's profile. Notification messages are "
"configured on the <a href=\"%s\">Expire Users settings</a> page.</p>"
msgstr ""
"<p><strong>Notification par email</strong><br />Des emails seront envoyés en "
"fonction des cases cochées sur le profil des utilisateurs. Les messages de "
"notification sont configurés sur la page <a href=\"%s\">Paramètres "
"d'expiration des utilisateurs</a>.</p>"
# : ../admin/help.php:56

msgid "Expiry Settings"
msgstr "Paramètres d'expiration"
# : ../admin/help.php:65

msgid ""
"<p><strong>Notification Emails</strong><br />These emails are sent if you "
"have checked the checkboxes on a user's profile.</p>"
msgstr ""
"<p><strong>Notification par email</strong><br />Des emails seront envoyés en "
"fonction des cases cochées sur le profil des utilisateurs.</p>"
# : ../admin/help.php:80

msgid "Expire Users Plugin"
msgstr "Politique d'expiration"
# : ../admin/help.php:82 ../admin/plugin.php:22

msgid "Documentation"
msgstr "Documentation"
# : ../admin/help.php:83

msgid "Support Forum"
msgstr "Forum d'aide"
# : ../admin/help.php:84

msgid "Contribute at Github"
msgstr "Contribuer à GitHub"
# : ../admin/help.php:85

msgid "Submit an Issue"
msgstr "Soumettre un commentaire"
# : ../admin/notifications.php:27

msgid "User Expired Notification"
msgstr "Activer la notification par email à l'utilisateur"
# : ../admin/notifications.php:28

msgid "This email is sent to a user when their login details expire."
msgstr ""
"Cet email est automatiquement envoyé à l'utilisateur lorsque la date de fin "
"de validité de son compte est atteinte."
# : ../admin/notifications.php:33

msgid "User Expired Admin Notification"
msgstr "Activer la notification par email à l'administrateur"
# : ../admin/notifications.php:34

msgid ""
"This email is sent to the WordPress admin email address when a user expires."
msgstr ""
"Cet email est automatiquement envoyé à l'administrateur lorsque le compte "
"d'un utilisateur a atteint la date de fin de validité."
# : ../admin/notifications.php:71

msgid "Notification"
msgstr "Notification"
# : ../admin/notifications.php:72

msgid "Message"
msgstr "Message"
# : ../admin/notifications.php:149

msgid "No notification defined."
msgstr "Aucune notification définie."
# : ../admin/plugin.php:21

msgid "https://github.com/benhuson/expire-users"
msgstr "https://github.com/benhuson/expire-users"
# : ../admin/plugin.php:21

msgid "GitHub"
msgstr "GitHub"
# : ../admin/plugin.php:22

msgid "https://github.com/benhuson/expire-users/wiki"
msgstr "https://github.com/benhuson/expire-users/wiki"
# : ../admin/plugin.php:36

msgid "Settings"
msgstr "Paramètres"
# : ../admin/settings.php:14

msgid "Expire Settings"
msgstr "Règles d'expiration"
# : ../admin/settings.php:82

msgid "Expire Users Settings"
msgstr "Règles d'expiration des comptes utilisateur"
# : ../admin/settings.php:86

msgid "Options saved"
msgstr "Les paramètres ont été enregistrés."
# : ../admin/settings.php:101

msgid "Registered User Expiry Settings"
msgstr "Réglages des paramètres d'expiration"
# : ../admin/settings.php:105

msgid ""
"Automatically set expiry date for new users who register via the "
"registration form."
msgstr ""
"Calculer automatiquement la date de fin de validité pour les nouveaux "
"utilisateurs qui s'inscrivent via le formulaire d'inscription."
# : ../admin/settings.php:194

msgid "Notification Emails"
msgstr "Réglages des notifications par email"
# : ../admin/settings.php:195

msgid ""
"These emails are sent if you have checked the checkboxes on a user's profile."
msgstr ""
"Des emails seront envoyés en fonction des cases cochées sur le profil des "
"utilisateurs."
# : ../admin/settings.php:196

msgid ""
"You may use the following placeholders in the notification email messages "
"below:"
msgstr ""
"Vous pouvez utiliser les variables suivantes dans les messages de "
"notification définis ci-dessous :"
# : ../admin/settings.php:200

msgid "Save Options"
msgstr "Enregistrer les paramètres"
# : ../includes/expire-user.php:92

msgid " @ "
msgstr " @ "
# : ../includes/expire-user.php:93
# , php-format

msgid "Expires: <strong>%s</strong>"
msgstr "Expire : <strong>%s</strong>"
# : ../includes/expire-user.php:94
# , php-format

msgid "Expired: <strong class=\"expire-user-expired\">%s</strong>"
msgstr "Expiré : <strong class=\"expire-user-expired\">%s</strong>"
# : ../includes/expire-user.php:95

msgid "Expire: <strong>Never</strong>"
msgstr "Expiration : <strong>Jamais</strong>"
# : ../includes/expire-users.php:96
# , php-format

msgid "Your login details to %%sitename%% have expired"
msgstr "Votre accès au site %%sitename%% a expiré"
# : ../includes/expire-users.php:109
# , php-format

msgid "Login details to %%sitename%% have expired (%%username%%)"
msgstr "L'accès au site %%sitename%% a expiré pour l'utilisateur %%username%%"
# : ../includes/expire-users.php:160
# , php-format

msgid "Your access to %%sitename%% has expired."
msgstr "Votre accès au site %%sitename%% a expiré."
# : ../includes/expire-users.php:167
# , php-format

msgid ""
"Access to %%sitename%% has expired for %%name%% (%%username%%) on "
"%%expirydate%%"
msgstr ""
"L'accès au site %%sitename%% a expiré pour l'utilisateur %%name%% (%%username"
"%%) le %%expirydate%%."
# : ../includes/expire-users.php:185

msgid "<strong>ERROR</strong>: Your user details have expired."
msgstr "<strong>Erreur :</strong>votre compte utilisateur a expiré !"
# : ../includes/expire-users.php:198

msgid ""
"<strong>ERROR</strong>: Your user details have expired so you are no longer "
"able to reset your password."
msgstr ""
"<strong>Erreur :</strong>votre compte utilisateur a expiré, c'est pour cela "
"que vous n&#39;êtes plus en mesure de réinitialiser votre mot de passe."
# : ../includes/shortcodes.php:22

msgid "M d, Y"
msgstr "d/m/Y"
# : ../includes/shortcodes.php:23
# , php-format

msgid "Expires %s"
msgstr "Expire %s"
# : ../includes/shortcodes.php:24
# , php-format

msgid "Expired %s"
msgstr "Expiré %s"
# : ../includes/shortcodes.php:25

msgid "Never Expire"
msgstr "N'expire jamais"

**Comment by benhuson** [comment]
I have made some updates to the plugin that requires updates to the language files.
Please could you review the most recent version of the files and make any updates, and I will ensure the translation is in the next version release.

https://github.com/benhuson/expire-users

**Comment by benhuson** [comment]
You can now translate via https://translate.wordpress.org/projects/wp-plugins/expire-users
