### ISSUE TITLE
Hook expire-users into custom registration forms?

### ISSUE THREAD

**Issue by dburges** [benhuson/expire-users#36]
This plugin does exactly what I need, but is not working with WooCommerce. I have WC configured to register new users when they place their first order. Is there a simple way to connect expire-users to this or other custom forms that use the register-user class? Thanks.

**Comment by martinchamrad** [comment]
Did you figure it out?

**Comment by dburges** [comment]
No, I switched to using a different plugin to achieve what I needed.

martinchamrad wrote:

**Comment by ksnellma** [comment]
Can you tell me which plugin, please? I also need this.

**Comment by vlsg** [comment]
@dburges please let us know what other plugin you used.  TIA

**Comment by abhijagtap73** [comment]
@dburges what exactly problem u getting with wc?
