### ISSUE TITLE
Incompatibility with the bbPress plug-in

### ISSUE THREAD

**Issue by euene** [benhuson/expire-users#37]
When an administrator tries to edit a user's profile from the bbPress front-end (_/forums/users/username/edit/_) there is an error:

```
Fatal error: Call to undefined function wp_dropdown_roles() in \wp-content\plugins\expire-users\admin\expire-user.php on line 182
```

Non-administrators don't get this error (i.e when a regular user tries to update their own profile).

Could be related to [this](https://github.com/benhuson/expire-users/commit/69af00962fcd582483ef12c1965383f62382a121).

**Comment by benhuson** [comment]
Thanks for highlight this.

Yes, it is related to that issue.
I'll try to find time to test and merge that.
