### ISSUE TITLE
Expire user at particular time on same day

### ISSUE THREAD

**Issue by abhijagtap73** [benhuson/expire-users#41]
Hi admin, i want to expire user on same day and change password by random one but i did observe its not expire on same day it take action on next day at 6 am. so what should i do to expire user as per time given.

**Comment by vlsg** [comment]
I have the same issue.  I am trying to test this new plugin so I set my test user to expire in 2 minutes from when i save the user, but then when I log out the user I can still log in just fine after the 2 minutes has passed.

**Comment by abhijagtap73** [comment]
@vlsg i had same issue it resolved by set wordpress timezone to local. so check your current wordpress timezone. i think it will work for u. :+1:

**Comment by vlsg** [comment]
@abhijagtap73 Thank you so much!
