### ISSUE TITLE
Expired users can still sign in (1.0.2 on WP 4.7.5)

### ISSUE THREAD

**Issue by jarnell** [benhuson/expire-users#48]
Seems like the authenticate hook calling Expire_User->authenticate(...) has too low priority. Changing it to 30 blocks expired users again. I made a temporary solution by chaining another call to it in my functions.php.

```
function call_expire_users_authenticate($user, $username, $password) {
  global $expire_users;
  return $expire_users->authenticate($user, $username, $password);
}

add_filter('authenticate', 'call_expire_users_authenticate', 30, 3);
```

**Comment by benhuson** [comment]
Fixed in https://github.com/benhuson/expire-users/commit/f0cd76c4daee1b3c90a3bcbde83381c4ada11841
