### ISSUE TITLE
Unable to log in with Expire Users!!!

### ISSUE THREAD

**Issue by benhuson** [benhuson/expire-users#62]
https://wordpress.org/support/topic/unable-to-log-in-with-expire-users/
https://wordpress.org/support/topic/plugin-is-death-do-you-now-similar/
https://wordpress.org/support/topic/error-your-user-details-have-expired/
https://wordpress.org/support/topic/this-plugin-is-dead-now-3/

**Comment by loreboldo** [comment]
I think this can be fixed by changing expire-users.php from 
`/**
	 * Logout Expired Logged In User
	 */
	public function logout_expired_logged_in_user() {

		if ( is_user_logged_in() ) {

			// Expire user if past expire date
			$user = new Expire_User( absint( get_current_user_id() ) );
			$expire = $user->maybe_expire();

			// Note expired date and logout
			if ( $expire ) {
				$user->set_expire_timestamp( current_time( 'timestamp' ) );
				$user->save_user();
				wp_clear_auth_cookie();
			}

		}

	}`

to this

`/**
	 * Logout Expired Logged In User
	 */
	public function logout_expired_logged_in_user() {

		if ( is_user_logged_in() ) {

			// Expire user if past expire date
			$user = new Expire_User( absint( get_current_user_id() ) );
			$expire = $user->maybe_expire();

			// Note expired date and logout
			if ( $expire ) {
				if ( $user->on_expire_user_remove_expiry ) {
					$user->remove_expire_date();
					$user->save_user();
				} else {
					$user->set_expire_timestamp( current_time( 'timestamp' ) );
					$user->save_user();
					wp_clear_auth_cookie();
				}
			}

		}

	}`

Tested on my installation and it works.
